serverAddr = "66.112.215.31"
serverPort = 7000

[[proxies]]
name = "web0"
type = "http"
localPort = 8080
customDomains = ["blldxt91fy.frps.grayless.top"]

[[proxies]]
name = "web1"
type = "http"
localPort = 8081
customDomains = ["comblldxtfy.frps.grayless.top"]

[[proxies]]
name = "hzm"
type = "http"
localPort = 4152
customDomains = ["comblldxthzm.frps.grayless.top"]

[[proxies]]
name = "platform"
type = "http"
localPort = 8187
customDomains = ["platform.frps.grayless.top"]
